#!/bin/bash
set -e

if command -v update-desktop-database >/dev/null; then
  update-desktop-database -q /usr/share/applications
fi

if command -v gtk-update-icon-cache >/dev/null; then
  gtk-update-icon-cache -f -t /usr/share/pixmaps || true
fi

exit 0
