name: Build Termyt Artifacts

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Version from Control File
        id: pkg_info
        run: |
          # reading  ver
          VERSION=$(grep -i '^Version:' DEBIAN/control | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Debian Package
        run: |
          mkdir -p build/DEBIAN

          cp -r usr build/
          cp DEBIAN/* build/DEBIAN/

          chmod +x build/usr/bin/termyt
          chmod +x build/DEBIAN/postinst || true
          chmod +x build/DEBIAN/postrm || true
          chmod 644 build/usr/share/applications/termyt.desktop

          dpkg-deb --build build termyt_${{ env.VERSION }}_all.deb

      - name: Build Binary Archives (Zip & Tar.gz)
        run: |
          # compress usr folder
          zip -r termyt_${{ env.VERSION }}.zip usr/
          tar -czvf termyt_${{ env.VERSION }}.tar.gz usr/

      - name: Build Source Code Archives
        run: |
          # uses git archive for creating packages
          git archive --format=zip --output=termyt_${{ env.VERSION }}_source.zip HEAD
          git archive --format=tar.gz --output=termyt_${{ env.VERSION }}_source.tar.gz HEAD

      - name: Upload All Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: termyt-artifacts-v${{ env.VERSION }}
          path: |
            *.deb
            *.zip
            *.tar.gz
